In [2]:
from datascience import *

## Python ##

In [3]:
songs2 = Table.read_table('/home/jovyan/shared/Data/songs2.csv')
songs2

name                          | artist         | duration
The Little Things             | Colbie Caillat | 225
The Regality Dance            | Elvenking      | 347
Come Out Swinging             | The Offspring  | 167
You Make Me Like Charity      | The Knife      | 185
Cat People (Putting Out Fire) | David Bowie    | 402
Attack The Doctor             | Blockhead      | 346
Sorry But It's Over           | dredg          | 249
Scarlette                     | Sevdaliza      | 205
Green Mind                    | Dinosaur Jr.   | 299
Whoever She Is                | The Maine      | 221
... (22485 rows omitted)

In [4]:
1+2

3

In [5]:
3 == 3

True

In [6]:
2-3

-1

## Names ##

In [7]:
status = True

In [9]:
if status == True:
    print(status)

True

## Functions and Call Expressions

In [13]:
def max(x, y):
    if x < y:
        return y
    elif x > y:
        return x
    else: 
        return None 

def abs(x):
    if x < 0:
        return -x
    else:
        return x

In [14]:
max(1,4)

4

In [15]:
max(4,1)

4

In [16]:
max(4,4)

## Tables

In [17]:
songs2 = Table.read_table('/home/jovyan/shared/Data/songs2.csv')
songs2

name                          | artist         | duration
The Little Things             | Colbie Caillat | 225
The Regality Dance            | Elvenking      | 347
Come Out Swinging             | The Offspring  | 167
You Make Me Like Charity      | The Knife      | 185
Cat People (Putting Out Fire) | David Bowie    | 402
Attack The Doctor             | Blockhead      | 346
Sorry But It's Over           | dredg          | 249
Scarlette                     | Sevdaliza      | 205
Green Mind                    | Dinosaur Jr.   | 299
Whoever She Is                | The Maine      | 221
... (22485 rows omitted)

In [18]:
songs2.show(3)

## Another table

In [ ]:
Arrests = Table.read_table('/home/jovyan/shared/Data/Police_Arrests_Made.csv')
Arrests