# STOR 120: Class 4 - Building Tables

In [82]:
from datascience import *
import numpy as np

## Arrays

In [83]:
heights = make_array(67, 60, 71, 63, 65)
heights

array([67, 60, 71, 63, 65])

In [84]:
heights / 12

array([ 5.58333333,  5.        ,  5.91666667,  5.25      ,  5.41666667])

In [85]:
len(heights)

5

In [86]:
sum(heights)

326

In [87]:
sum(heights) / len(heights)

65.200000000000003

In [88]:
np.average(heights)

65.200000000000003

In [89]:
strings_array = make_array('ok', 'ya', 'hm')
strings_array

array(['ok', 'ya', 'hm'],
      dtype='<U2')

In [90]:
# strings_array * 2

In [91]:
heights.item(3)

63

In [92]:
heights.item(0)

67

In [93]:
strings_array.item(0)

'ok'

## Ranges ##

In [94]:
make_array(0, 1, 2, 3, 4, 5, 6)

array([0, 1, 2, 3, 4, 5, 6])

In [95]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [96]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [97]:
np.arange(5, 11)

array([ 5,  6,  7,  8,  9, 10])

In [98]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [99]:
np.arange(0, 21, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [100]:
np.arange(0, 1, 0.1)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9])

In [101]:
a = np.arange(8)

In [102]:
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [103]:
# a.item(8)

In [104]:
a.item(7)

7

In [105]:
a.item(-1)

7

## Creating a Table from Scratch ##

In [106]:
streets = make_array('Franklin', 'East Rosemary', 'North')
streets

array(['Franklin', 'East Rosemary', 'North'],
      dtype='<U13')

In [107]:
Table()

In [108]:
North_of_Campus = Table().with_column('Streets', streets)
North_of_Campus

Streets
Franklin
East Rosemary
North

In [109]:
North_of_Campus.with_column('Blocks North of campus', np.arange(3))

Streets       | Blocks North of campus
Franklin      | 0
East Rosemary | 1
North         | 2

In [110]:
North_of_Campus

Streets
Franklin
East Rosemary
North

In [111]:
North_of_Campus = North_of_Campus.with_column('Blocks North of campus', np.arange(3))
North_of_Campus

Streets       | Blocks North of campus
Franklin      | 0
East Rosemary | 1
North         | 2

In [112]:
North_of_Campus.labels

('Streets', 'Blocks North of campus')

In [113]:
North_of_Campus.num_columns

2

In [114]:
North_of_Campus.num_rows

3

### Minard ###

In [115]:
minard = Table.read_table('../../shared/Data/minard.csv')
minard

Longitude | Latitude | City        | Direction | Survivors
24        | 54.9     | Kaunas      | Advance   | 340000
30.2      | 55.2     | Vitebsk     | Advance   | 175000
32        | 54.8     | Smolensk    | Advance   | 145000
37.6      | 55.8     | Moscow      | Advance   | 100000
34.3      | 55.2     | Vyazma      | Retreat   | 55000
32        | 54.6     | Smolensk    | Retreat   | 24000
30.4      | 54.4     | Orsha       | Retreat   | 20000
26.8      | 54.3     | Maladyechna | Retreat   | 12000
24.1      | 54.4     | Kaunas      | Retreat   | 4000

What percentage of Napoleon’s troops were still alive in each city of the advance and retreat?

In [116]:
minard.select('City')

City
Kaunas
Vitebsk
Smolensk
Moscow
Vyazma
Smolensk
Orsha
Maladyechna
Kaunas

In [117]:
minard.column('City')

array(['Kaunas', 'Vitebsk', 'Smolensk', 'Moscow', 'Vyazma', 'Smolensk',
       'Orsha', 'Maladyechna', 'Kaunas'],
      dtype='<U11')

In [118]:
minard.column('Survivors')

array([340000, 175000, 145000, 100000,  55000,  24000,  20000,  12000,
         4000])

In [119]:
initial_size = minard.column('Survivors').item(0)
initial_size

340000

In [120]:
minard.column('Survivors') / initial_size

array([ 1.        ,  0.51470588,  0.42647059,  0.29411765,  0.16176471,
        0.07058824,  0.05882353,  0.03529412,  0.01176471])

In [121]:
minard = minard.with_column(
    'Pct alive', 
    minard.column('Survivors') / initial_size)
minard

Longitude | Latitude | City        | Direction | Survivors | Pct alive
24        | 54.9     | Kaunas      | Advance   | 340000    | 1
30.2      | 55.2     | Vitebsk     | Advance   | 175000    | 0.514706
32        | 54.8     | Smolensk    | Advance   | 145000    | 0.426471
37.6      | 55.8     | Moscow      | Advance   | 100000    | 0.294118
34.3      | 55.2     | Vyazma      | Retreat   | 55000     | 0.161765
32        | 54.6     | Smolensk    | Retreat   | 24000     | 0.0705882
30.4      | 54.4     | Orsha       | Retreat   | 20000     | 0.0588235
26.8      | 54.3     | Maladyechna | Retreat   | 12000     | 0.0352941
24.1      | 54.4     | Kaunas      | Retreat   | 4000      | 0.0117647

In [122]:
minard.set_format('Pct alive', PercentFormatter)

Longitude | Latitude | City        | Direction | Survivors | Pct alive
24        | 54.9     | Kaunas      | Advance   | 340000    | 100.00%
30.2      | 55.2     | Vitebsk     | Advance   | 175000    | 51.47%
32        | 54.8     | Smolensk    | Advance   | 145000    | 42.65%
37.6      | 55.8     | Moscow      | Advance   | 100000    | 29.41%
34.3      | 55.2     | Vyazma      | Retreat   | 55000     | 16.18%
32        | 54.6     | Smolensk    | Retreat   | 24000     | 7.06%
30.4      | 54.4     | Orsha       | Retreat   | 20000     | 5.88%
26.8      | 54.3     | Maladyechna | Retreat   | 12000     | 3.53%
24.1      | 54.4     | Kaunas      | Retreat   | 4000      | 1.18%

In [123]:
minard.column("Pct alive")

array([ 1.        ,  0.51470588,  0.42647059,  0.29411765,  0.16176471,
        0.07058824,  0.05882353,  0.03529412,  0.01176471])

In [127]:
minard = minard.append_column("Pct alive 2", minard.column("Survivors") / minard.column("Survivors").item(0))
minard

Longitude | Latitude | City        | Direction | Survivors | Pct alive | Pct alive 2
24        | 54.9     | Kaunas      | Advance   | 340000    | 100.00%   | 1
30.2      | 55.2     | Vitebsk     | Advance   | 175000    | 51.47%    | 0.514706
32        | 54.8     | Smolensk    | Advance   | 145000    | 42.65%    | 0.426471
37.6      | 55.8     | Moscow      | Advance   | 100000    | 29.41%    | 0.294118
34.3      | 55.2     | Vyazma      | Retreat   | 55000     | 16.18%    | 0.161765
32        | 54.6     | Smolensk    | Retreat   | 24000     | 7.06%     | 0.0705882
30.4      | 54.4     | Orsha       | Retreat   | 20000     | 5.88%     | 0.0588235
26.8      | 54.3     | Maladyechna | Retreat   | 12000     | 3.53%     | 0.0352941
24.1      | 54.4     | Kaunas      | Retreat   | 4000      | 1.18%     | 0.0117647

In [128]:
minard.set_format('Pct alive 2', PercentFormatter)

Longitude | Latitude | City        | Direction | Survivors | Pct alive | Pct alive 2
24        | 54.9     | Kaunas      | Advance   | 340000    | 100.00%   | 100.00%
30.2      | 55.2     | Vitebsk     | Advance   | 175000    | 51.47%    | 51.47%
32        | 54.8     | Smolensk    | Advance   | 145000    | 42.65%    | 42.65%
37.6      | 55.8     | Moscow      | Advance   | 100000    | 29.41%    | 29.41%
34.3      | 55.2     | Vyazma      | Retreat   | 55000     | 16.18%    | 16.18%
32        | 54.6     | Smolensk    | Retreat   | 24000     | 7.06%     | 7.06%
30.4      | 54.4     | Orsha       | Retreat   | 20000     | 5.88%     | 5.88%
26.8      | 54.3     | Maladyechna | Retreat   | 12000     | 3.53%     | 3.53%
24.1      | 54.4     | Kaunas      | Retreat   | 4000      | 1.18%     | 1.18%